#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index
connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
recherche:
    path: /recherche
    controller: App\Controller\RechercheController::index
compte:
    path: /compte
    controller: App\Controller\EspaceClientController::index
reservation:
    path: /reservation
    controller: App\Controller\ReservationController::index
confirm_reservation:
    path: /confirm_reservation
    controller: App\Controller\ConfirmReservationController::index
paiement:
    path: /paiement
    controller: App\Controller\PaiementController::index
contact:
    path: /contact
    controller: App\Controller\ServiceContactController::index
liaison:
    path: /liaison
    controller: App\Controller\LiaisonController::index
login:
    path: /login
    controller: App\Controller\SecurityController::index
register:
    path: /register
    controller: App\Controller\RegistrationController::index
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /accueil
        permanent: true